# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rlgam <- function(shape) {
    .Call('_SharedForest_rlgam', PACKAGE = 'SharedForest', shape)
}

rcpparma_hello_world <- function() {
    .Call('_SharedForest_rcpparma_hello_world', PACKAGE = 'SharedForest')
}

rcpparma_outerproduct <- function(x) {
    .Call('_SharedForest_rcpparma_outerproduct', PACKAGE = 'SharedForest', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_SharedForest_rcpparma_innerproduct', PACKAGE = 'SharedForest', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_SharedForest_rcpparma_bothproducts', PACKAGE = 'SharedForest', x)
}

SharedBart <- function(X, Y, W, delta, X_test, W_test, hypers_, opts_) {
    .Call('_SharedForest_SharedBart', PACKAGE = 'SharedForest', X, Y, W, delta, X_test, W_test, hypers_, opts_)
}

MixedBart <- function(X, Y, W, delta, cluster, clusterw, hypers_, opts_) {
    .Call('_SharedForest_MixedBart', PACKAGE = 'SharedForest', X, Y, W, delta, cluster, clusterw, hypers_, opts_)
}

