# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rlgam <- function(shape) {
    .Call('_GammaForest_rlgam', PACKAGE = 'GammaForest', shape)
}

rcpparma_hello_world <- function() {
    .Call('_GammaForest_rcpparma_hello_world', PACKAGE = 'GammaForest')
}

rcpparma_outerproduct <- function(x) {
    .Call('_GammaForest_rcpparma_outerproduct', PACKAGE = 'GammaForest', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_GammaForest_rcpparma_innerproduct', PACKAGE = 'GammaForest', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_GammaForest_rcpparma_bothproducts', PACKAGE = 'GammaForest', x)
}

GammaBart <- function(X, Y, W, delta, X_test, W_test, hypers_, opts_) {
    .Call('_GammaForest_GammaBart', PACKAGE = 'GammaForest', X, Y, W, delta, X_test, W_test, hypers_, opts_)
}

